#!/usr/bin/env node

const util = require('util');
const fs = require('mz/fs');

async function run() {

    for (host of await fs.readdir('/mnt')) {
        const httpHostnames = new Array();
        const httpsHostnames = new Array();
        
        for (site of await fs.readdir(`/mnt/${host}/sites`)) {
            const siteConfigPath = `/mnt/${host}/sites/${site}/site.json`;

            if (await fs.exists(siteConfigPath)) {
                const siteConfig = require(siteConfigPath);
                const siteHostnames = new Set();

                siteHostnames.add(siteConfig.primary_hostname);
                siteConfig.hostnames.forEach(hostname => siteHostnames.add(hostname));

                if (siteConfig.ssl) {
                    siteHostnames.forEach(hostname => httpsHostnames.push(hostname));
                } else {
                    siteHostnames.forEach(hostname => httpHostnames.push(hostname));
                }
            }
        }

        console.log('server {');
        console.log('    listen 10.90.8.238:80;');
        console.log(`    server_name ${httpHostnames.join(' ')};`);
        console.log('    location / {');
        console.log(`        proxy_pass http://${host}:80;`);
        console.log('    }');
        console.log('}\n');
    }

/*
    //console.log('hosts', hosts.map(host => host.keys()));
    for ([host, sites] of hosts.entries()) {
        console.log(host, Array.from(sites.keys()));
    }
*/
/*
    console.log('hosts', hosts);
    console.log('ssl sites', sslSites);
    console.log('hostnames', hostnames);*/
}


run();

